node {
  
   try{
    stage ('Preparation') {
        git 'https://github.com/rautate/maven-examples.git'
         mvnHome = tool 'maven-default'
    }
     stage ('mvn install') {
       withMaven(jdk: 'java-default', maven: 'maven-default') {
                    sh 'mvn -B -DskipTests clean install'
                }
   }
  catch(err)
  {
    currentBuild.result ="FAILURE"
    step([$class: 'Mailer', notifyUnstableEveryBuild:true, recipients:'', sendToIndividuals: true])
    throw err
  }
}
